{ PFoo aliases for Dialogs/cluster/list class types in tv3. }
type
  PDialog         = TDialog;
  PStaticText     = TStaticText;
  PLabel          = TLabel;
  PButton         = TButton;
  PInputLine      = TInputLine;
  PCluster        = TCluster;
  PRadioButtons   = TRadioButtons;
  PCheckBoxes     = TCheckBoxes;
  PListBox        = TListBox;
  PListViewer     = TListViewer;
  PHistory        = THistory;
  PHistoryWindow  = THistoryWindow;
  PHistoryViewer  = THistoryViewer;
  PValidator      = TValidator;
